In [1]:
# Import dependencies
import random
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import traceback
import gmaps
# Import the API key.
from config import g_key

In [2]:
weather_db = "data\WeatherPy_challenge.csv"

In [3]:
weather_df = pd.read_csv(weather_db)
weather_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
0,Busselton,AU,2020-04-20 04:43:58,-33.65,115.33,69.01,65,97,11.99,light rain,0.30,0.0
1,Laguna,US,2020-04-20 04:39:00,38.42,-121.42,60.01,67,1,5.82,clear sky,0.00,0.0
2,Naro Moru,KE,2020-04-20 04:44:00,-0.17,37.02,58.30,53,100,1.77,light rain,2.48,0.0
3,Port Alfred,ZA,2020-04-20 04:32:14,-33.59,26.89,69.01,64,0,4.61,clear sky,0.00,0.0
4,Arraial Do Cabo,BR,2020-04-20 04:32:26,-22.97,-42.03,70.61,81,46,7.05,scattered clouds,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
586,Buchanan,LR,2020-04-20 04:54:32,5.88,-10.05,78.80,85,100,4.63,overcast clouds,0.00,0.0
587,Constitucion,CL,2020-04-20 04:54:32,-35.33,-72.42,56.05,67,93,8.37,overcast clouds,0.00,0.0
588,Warri,NG,2020-04-20 04:54:34,5.52,5.75,77.49,88,100,2.30,overcast clouds,0.00,0.0
589,Carutapera,BR,2020-04-20 04:52:10,-1.20,-46.02,78.91,86,46,6.40,scattered clouds,0.00,0.0
590,Argentan,FR,2020-04-20 04:54:35,48.75,-0.02,48.20,93,92,5.82,overcast clouds,0.00,0.0

In [10]:
# Ask customer to add a minimum and maximum temperature value.

# Minimum Temperature
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Maximum Temperature
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

# Climate type.
rain_q = str(input("Do you want it to be raining? (yes/no) "))
snow_q = str(input("Do you want it to be snowing? (yes/no) "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90
Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [11]:
if rain_q == "no" and snow_q == "no":
    ideal_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                           (weather_df["Max Temp"] >= min_temp) & \
                                           (weather_df["Rain Inches (last 3 hrs)"] == 0) & \
                                           (weather_df["Snow Inches (last 3 hrs)"] == 0)]
elif rain_q == "yes" and snow_q == "no":
    ideal_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                   (weather_df["Max Temp"] >= min_temp) & \
                                   (weather_df["Rain Inches (last 3 hrs)"] != 0) & \
                                   (weather_df["Snow Inches (last 3 hrs)"] == 0)]
elif rain_q == "no" and snow_q == "yes":
    ideal_cities_df = weather_df.loc[(weather_df["Max Temp"] <= max_temp) & \
                                   (weather_df["Max Temp"] >= min_temp) & \
                                   (weather_df["Rain Inches (last 3 hrs)"] == 0) & \
                                   (weather_df["Snow Inches (last 3 hrs)"] != 0)]
else:
    print("No cities")

In [12]:
ideal_cities_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain Inches (last 3 hrs),Snow Inches (last 3 hrs)
8,Bengkulu,ID,2020-04-20 04:33:20,-3.80,102.27,88.72,59,47,6.26,scattered clouds,0.0,0.0
13,Karia,NG,2020-04-20 04:44:08,11.73,11.16,79.02,14,52,4.79,broken clouds,0.0,0.0
15,Hambantota,LK,2020-04-20 04:41:04,6.12,81.12,89.60,79,20,13.87,few clouds,0.0,0.0
19,Geraldton,AU,2020-04-20 04:39:08,-28.77,114.60,75.00,46,75,13.87,broken clouds,0.0,0.0
21,Pindiga,NG,2020-04-20 04:44:14,9.98,10.93,77.02,59,56,12.80,broken clouds,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
581,Kismayo,SO,2020-04-20 04:54:16,-0.36,42.55,83.55,73,100,10.45,overcast clouds,0.0,0.0
582,Tarut,SA,2020-04-20 04:54:29,26.57,50.04,77.00,78,75,6.93,broken clouds,0.0,0.0
586,Buchanan,LR,2020-04-20 04:54:32,5.88,-10.05,78.80,85,100,4.63,overcast clouds,0.0,0.0
588,Warri,NG,2020-04-20 04:54:34,5.52,5.75,77.49,88,100,2.30,overcast clouds,0.0,0.0
589,Carutapera,BR,2020-04-20 04:52:10,-1.20,-46.02,78.91,86,46,6.40,scattered clouds,0.0,0.0

In [13]:
# Create a Hotel DataFrame.

hotel_df = ideal_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

hotel_df["Hotel Name"] = ""

hotel_df.head()

          City Country  Max Temp Current Description    Lat     Lng Hotel Name
8     Bengkulu      ID     88.72    scattered clouds  -3.80  102.27
13       Karia      NG     79.02       broken clouds  11.73   11.16
15  Hambantota      LK     89.60          few clouds   6.12   81.12
19   Geraldton      AU     75.00       broken clouds -28.77  114.60
21     Pindiga      NG     77.02       broken clouds   9.98   10.93

In [14]:
import gmaps
from config import g_key

In [15]:
# Set parameters to search for hotel.
hotel_parameters = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key}

In [18]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    hotel_parameters["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, hotel_parameters).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [20]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,Bengkulu,ID,88.72,scattered clouds,-3.80,102.27,Grage Hotel Bengkulu
13,Karia,NG,79.02,broken clouds,11.73,11.16,
15,Hambantota,LK,89.60,few clouds,6.12,81.12,Bungalow 63
19,Geraldton,AU,75.00,broken clouds,-28.77,114.60,Broadwater Mariner Resort
21,Pindiga,NG,77.02,broken clouds,9.98,10.93,Accommodation Center

In [21]:
## Marker Layer Map.

# Heatmap of temperature for the vacation locations.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

# Plot.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Add Pop-Up Markers.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Plot.
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# Save the new dataframe as a CSV file to be used for Part 3
hotel_df.to_csv('data\WeatherPy_vacation.csv', index=False)